server:
  port: 9094

spring:
  application:
    name: app-client-turbine

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@eureka1:7001/eureka
      #defaultZone: http://admin:admin@eureka1:7001/eureka,http://admin:admin@eureka2:7002/eureka,http://admin:admin@eureka3:7003/eureka

turbine:
  # 注入euraka 的spring.application.name
  app-config: APP-ORDER,APP-PRODUCT
  cluster-name-expression: new String("default")
