server:
  port: 7003

eureka:
  server:
    eviction-interval-timer-in-ms: 10000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #关闭保护模式,开启则不清理掉线无效节点
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@eureka1:7001/eureka,http://admin:admin@eureka2:7002/eureka,http://admin:admin@eureka3:7003/eureka
  instance:
    instance-id: ${spring.application.name}
    hostname: eureka3

spring:
  security:
    user:
      name: admin
      password: admin
  application:
    name: eureka-3