server:
  port: 8088

spring:
  application:
    name: app-stream-provider
  cloud:
    stream:
      rabbit:
        bindings:
          mic_user_output:
            producer:
              routingKeyExpression: '''mic_user_router_key'''
          mic_product_output:
            producer:
              routingKeyExpression: '''mic_product_router_key'''
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        mic_rabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                addresses: localhost
                port: 5672
                username: admin
                password: admin
                virtual-host: /
      bindings: # 服务的整合处理
        mic_user_output: # 这个名字是一个通道的名称
          destination: mic_exchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: mic_rabbit # 设置要绑定的消息服务的具体设置
        mic_product_output: # 这个名字是一个通道的名称
          destination: mic_exchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: mic_rabbit # 设置要绑定的消息服务的具体设置
