server:
  port: 7103

spring:
  application:
    name: app-sleuth-zipkin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.70:3306/zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Yzwl2018
  sleuth:
    enabled: false

management:
  metrics:
    web:
      server:
        auto-time-requests: false


zipkin:
  collector:
    sample-rate: 1.0
    http:
      enabled: false
    rabbitmq:
      addresses: localhost:5672
      password: guest
      queue: ${spring.application.name}
      username: guest
      virtual-host: /
  storage:
    type: mysql
#    mysql:
#      host: 192.168.1.70
#      port: 3306
#      username: root
#      password: Yzwl2018
#      db: zipkin