server:
  port: 8086

spring:
  application:
    name: app-zuul-gateway #同一服务多实例注入eureka时名字要相同
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@eureka1:7001/eureka
  #      defaultZone: http://admin:admin@eureka1:7001/eureka,http://admin:admin@eureka2:7002/eureka,http://admin:admin@eureka3:7003/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 心跳时间最大间隔，这段时间内注册中心没收到心跳请求则移除节点（默认是90秒）

info:
  app.name: ${spring.application.name}
  build.artifactId: $[project.artifactId]

### zuul config type 1
zuul:
  routes:
    APP-PRODUCT: /product-proxy/**
    APP-ORDER: /order-proxy/**
  ignored-services: "*"  #关闭后只能用zuul.routes的映射关系访问服务，开启时映射关系和eureka-id都能作为url访问
#  prefix: /panzervor/api #url统一前缀



### zuul config type 2
#zuul:
#  routes:
#    product-1:
#      path: /product-1-proxy/**
#      serviceId: APP-PRODUCT
#    product-2:
#      path: /product-2-proxy/**
#      url: http://localhost:8082/
