server:
  port: 7102

spring:
  application:
    name: app-config-bus-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/smothery/mic-config.git
          # 公开仓库可不填用户密码
          #username: smothery
          #password: 1234
          #search-paths:  #git上起始查找目录，可多个
          #basedir:   #本地下载目录
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka1:7001/eureka
  #      defaultZone: http://admin:admin@eureka1:7001/eureka,http://admin:admin@eureka2:7002/eureka,http://admin:admin@eureka3:7003/eureka
  instance:
    instance-id: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"